import { Pet } from './types';

export const PETS: Pet[] = [
  {
    id: '1',
    name: 'Buddy',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    ageGroup: 'Young',
    size: 'Large',
    gender: 'Male',
    location: 'San Francisco, CA',
    price: 350,
    description: 'Buddy is a quintessential Golden Retriever: friendly, loyal, and full of life. He was rescued from a local shelter and has since shown us his incredible capacity for love. He is always the first to greet you at the door with a wagging tail and a favorite tennis ball in his mouth.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAG43o26OI_7TbCAFoMZtQ34TwdR-z3a9dGfiX9maPkknWQfx5iuDdjgZgDMRsTOCw-BTP2TUAxjrYTTd3E0OcJJmr2cKhCVZ_8e0Vv1F47dAFqN4BhjiPjUEIh7t23hbbzReYdpRxXG9W5wzdmICa9WIXdU0YTXhhMIXpkDS4TVnDpfpIp1F7z60MFCXmTt1Auvr7WzffZo0PKZetNibu0UoLfVrPGq_n8TFbtCRPBrrXROKnFTHeUgY8-UQdlD5JmmqkJCNUEDXc',
    gallery: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB49KpCIfkyuoBIgB1D9LRbje6Mr-TwVo-MrIs_L7ZXtKBxs59osTuNnzYS3RyhgIUrr30lp5WtA-ID7goZ6U7x_G-a4xh8MyERL79cezDMPv3wEJwWIVA51mmFoOsbEoSPVojmDG4A6kc5drvJBPsi6NRZqguk4pgRqorH5xHfkgnz9j-Xxd87I3dU6ZSFMEFR_lyXyuaPgtxYKM1c28RQT4NamHiGGA7TEPF3Xv4VNDawoTlZIZz4G6E9caMWLMKPMVOkmPsLn4c',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB5Jpzq2gP_Sf3b46K51h68IVmZSTZapB1Jv0KfWtyHY3B0jPUmaReb3-QncnCGhJZ_IjWZY3KdLzCO-Qhhys9vt7EAlCm4zXw-5FfrEzyOecruP8IO2zcbJXdyj4QMjex2HaXP7MtBpOCjj4awmjAHRaiN_Lo9dKSM_-EY2gDTrWBrJgoPuvOYn6SshTBEt3WVjgr7HGB7Fu6JsqqPUWKsqCs6CF_BdytyQcL7hLVyF0Jplz1gAl4w0dGNmBoWyLbMivGmMgczLEg',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDvqTs6m3qw6m50ewasx4b9yDP5B8BlEVOmARRLVr6EGEnuc0rJbMKDoJyCCe0PpBQ2X5j2Piq3jimbuLpGBaDQibR4py895dQcjHxnBE2ck8_cdSbAAcAh2WYpgDzO_RZFHLm3QYwJIzj5aW4JVtjmDluoDrk-mRDQuuzG6OZ--vm7SOK9YElb7pU761zE36ClL1S7BxxE6CA0PR_Wz-y4XLyuaplCtaxXQ_sNBZNDBbT1VopwRcrNyD3zhQsvHsVNYAMzBvnqkZw'
    ],
    traits: ['Kid Friendly', 'Dog Friendly', 'House Trained', 'Loves Water', 'Fast Learner'],
    healthInfo: ['Up to date on vaccinations', 'Neutered', 'Microchipped', 'Heartworm negative'],
    isNew: true,
    energyLevel: 'High',
    weight: '65lbs'
  },
  {
    id: '2',
    name: 'Luna',
    type: 'Cat',
    breed: 'Domestic Shorthair',
    age: '1 year',
    ageGroup: 'Young',
    size: 'Small',
    gender: 'Female',
    location: 'Oakland, CA',
    price: 150,
    description: 'Luna is a sweet and gentle soul who loves to curl up in your lap. She was found as a stray but has adapted perfectly to indoor life.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBL_r_-SvwpKRATJsYnOuLf9EX8w4ja3l3E3zXDXTpsWIrkNgJsPVIjrr6VJahruVGGomZmV0dNlAzGdXuDKYxpNM3SD10VX6pWJ21QrQ8K-ZEe9QGciaB7WyYvxq8xauMYqcSs2Amph6E8Z3gvVqJR7pFNSiwtRdofTRhgzqPEh2-lySF8xZSXVrV1GIRJeq8lwWBoyR4yqZv5UtU2RJLGTSyFGGYbCFVQVk24ClIUAcJFSGRXAN7Ji4IfCTXLv4nJX7HrcK-k-fE',
    gallery: [],
    traits: ['Lap Cat', 'Quiet', 'Good with other cats'],
    healthInfo: ['Vaccinated', 'Spayed'],
    energyLevel: 'Low'
  },
  {
    id: '3',
    name: 'Max',
    type: 'Dog',
    breed: 'Beagle Mix',
    age: '4 years',
    ageGroup: 'Adult',
    size: 'Medium',
    gender: 'Male',
    location: 'San Jose, CA',
    price: 200,
    description: 'Max is an energetic Beagle mix who loves to follow his nose. He needs an active family with a fenced yard.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBUd2cAi061y0-Ir1Ud3r5-rkpn4Cg1UkoZl7R96vQCxfevNi7aaJ2SrBvPTS9qHXucRFdI72uBmOo-UbrpaUq1ctnuXvlCznxyKc4RjMBOzpE_TfUS-TaL0cqMXDtQ8ChYtM6c1i4DtyQv_GSSr8CRvR2qy9-cJj3cHhdri9a-PnL-PNiHyT6B_GPfw-p8Ib5uD-vimkuC6v5Q1utc1LmbKoEPkyboycPcIfkfI1O0qPk8zm6GtkI7kM5Zhvs9ntoOv0ZhSxEn8Bs',
    gallery: [],
    traits: ['Active', 'Scent-driven', 'Friendly'],
    healthInfo: ['Vaccinated', 'Neutered'],
    energyLevel: 'High'
  },
  {
    id: '4',
    name: 'Bella',
    type: 'Cat',
    breed: 'Persian Cat',
    age: '3 years',
    ageGroup: 'Adult',
    size: 'Small',
    gender: 'Female',
    location: 'Berkeley, CA',
    price: 180,
    description: 'Bella is a majestic Persian cat who enjoys being pampered. She has a calm temperament and loves a quiet environment.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBgWODiUM63wy_YmhWy8cbgvj3LSyPi5So-spvtDN8O4K1QpRgvF3se_w36RGdRXKtED9VLlmRAhGrVg2ky4t6MmETF94XKHKk4B55qUV5RJqegFmPPtH8mG5w4zYmPx3ad4yeTBMDkVkMH9mD9INvhvsNDR5A6CakjapgQyN4USfKCzKZlhDqwmOl6sYYkVwvJO4TpxV5orUvrVy60FK_HzFqVejn7K7xuawKJR8C40gm4qvSkooQWKeemqfRoELhhLKC-dyQY2GU',
    gallery: [],
    traits: ['Calm', 'Independent', 'Soft fur'],
    healthInfo: ['Vaccinated', 'Spayed'],
    energyLevel: 'Low'
  },
  {
    id: '5',
    name: 'Oliver',
    type: 'Cat',
    breed: 'Domestic Shorthair',
    age: '2 years',
    ageGroup: 'Young',
    size: 'Small',
    gender: 'Male',
    location: 'Houston, TX',
    price: 120,
    description: 'Oliver is a curious and playful ginger cat who loves exploring his surroundings.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDiGIruPvvrNrdI_0JTOiL331T_w50K3_vke3kfwhEktYJVmavE4e-WZTSwfi0wBMJvXn7gKH-JYGjcEY4R5CpEYSG7rEEppXuJI4EPTZO7Lvc4WqRLBeHe6yRlcKyPFugDxsCLGZDP-cNiP66HO6GjGp4s1o8W_KOpl7k94dlSWdZbb3hEWCejrIKs6D8udN5gUXLK8TRMpL0Y6fsaV0TT2aG4xmEVJEUCnZ-29TprRMvuUNMcedjU6MrVUCi9gVlVIgb_gsCLSxo',
    gallery: [],
    traits: ['Curious', 'Playful', 'Social'],
    healthInfo: ['Vaccinated', 'Neutered'],
    energyLevel: 'Medium'
  },
  {
    id: '6',
    name: 'Snowy',
    type: 'Rabbit',
    breed: 'Holland Lop Rabbit',
    age: '1 year',
    ageGroup: 'Young',
    size: 'Small',
    gender: 'Male',
    location: 'Dallas, TX',
    price: 50,
    description: 'Snowy is a fluffy Holland Lop rabbit who enjoys munching on carrots and being gently petted.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAjbm65px4gYTpk0t934wJTYOOH-XGS2CH0hagbzfywLGEtbXWCDrCr-Ys5F8DRXLTyP405qORRn1Gp2JJMo03QsgUb-o1FiRWjzXjOwv0lGTdyGoPusCrY1fJXUZQE0piySa9Gip_wfgXpmoRmkfLwnUmhyATHu9rbROWfN2_Ajsid3W4tv-NbBWJS1a78CcVoZpTw1ATdiDsYltV3tR-k27gbKYJThhjG4aQ_5ByyRnJqviHM-MxbD-jCs9fErpJuwbP5vBcFnQQ',
    gallery: [],
    traits: ['Fluffy', 'Gentle', 'Loves greens'],
    healthInfo: ['Health checked'],
    energyLevel: 'Low'
  },
  {
    id: '7',
    name: 'Charlie',
    type: 'Dog',
    breed: 'Beagle Mix',
    age: '3 years',
    ageGroup: 'Adult',
    size: 'Medium',
    gender: 'Male',
    location: 'Austin, TX',
    price: 300,
    description: 'Charlie is a friendly Beagle mix who gets along with everyone he meets.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCFsf-bEe5V5AlsGxDZ-5YlfwPS9lWznxTE0HDvOQKB6ghs9DWKRptkotFfMLbvV9MhvLGa7l87oDhLjtqY-YVsBZIIR39X8NAwM-ViSAAtTP2_eAbZknAEDOR4S3yqnUpt9WntFvTqRqBU0KMGVkWbSbHAYEgvhbw7-HxNbg92WmtzwXLOz8BdKTRauzr9BivUFwFjxWdlzEjRNNpYaXhwfLnG9OimaRufClhvVamJrhbrV3wxDzq3LDVGUCtJSDWbqkM5ny5b7e8',
    gallery: [],
    traits: ['Friendly', 'Good with kids', 'Vocal'],
    healthInfo: ['Vaccinated', 'Neutered'],
    energyLevel: 'Medium'
  },
  {
    id: '8',
    name: 'Misty',
    type: 'Cat',
    breed: 'Calico',
    age: '5 years',
    ageGroup: 'Adult',
    size: 'Small',
    gender: 'Female',
    location: 'San Antonio, TX',
    price: 95,
    description: 'Misty is a beautiful Calico cat who prefers a relaxed lifestyle.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB9eml5-o4YwAh5Xt3hiUy5j_GGQ4lJaxZulYJNTCutGwOTDv4lVhUS1-8S2jNrbOnbSPu_rNFWBwWN0xhcw8U9ane8fMK2odSP2raZeUwTrJ753yWvhI6xPt_q-uL0wZxEA6ueWyZvJchuU7rl4wiDU_fFEzrHHD41PXvDPVuvWrnpAA6Y6XGgL5O7jDck20WV7OTFB_An-ckgkAhpnCgTtLTtPJ4jwa-sIhzlxpdN2t9iJXusXdgEdaCZWqO1kxndEkrMLkLbkh8',
    gallery: [],
    traits: ['Relaxed', 'Independent', 'Colorful'],
    healthInfo: ['Vaccinated', 'Spayed'],
    energyLevel: 'Low'
  },
  {
    id: '9',
    name: 'Leo & Toby',
    type: 'Cat',
    breed: 'Siamese Mix (Bonded)',
    age: '3 months',
    ageGroup: 'Puppy/Kitten',
    size: 'Small',
    gender: 'Male',
    location: 'Austin, TX',
    price: 200,
    description: 'Leo and Toby are bonded brothers who must be adopted together. They are full of kitten energy!',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAyN9FHqqXStWg-xAusawrpEv-Eb5DPDTU1D8uqeKy-W5aF6TsNEhxysF0X_fEmZVbiwzUrjl1xwi55j2dii_rHr8_uDVKZm2GFRjg_IB90TOncey_xpZSEkDrNygDblzyr8g4M5a3YyvQOawSkdPXDCJLd3IOQQNhWM8w0OiRybKk4hVZhuHKGmg1Krksy303Ru3VA_c_Wx-1_NdZ4KwgmdqHFnF74Ox2Q-02vNCGEKJyOqpuhndDjFF-J5ZnSmWRFzpynSvquyLI',
    gallery: [],
    traits: ['Bonded pair', 'High energy', 'Playful'],
    healthInfo: ['Kitten shots started'],
    energyLevel: 'High'
  },
  {
    id: '10',
    name: 'Cooper',
    type: 'Dog',
    breed: 'Golden Retriever',
    age: '2 years',
    ageGroup: 'Young',
    size: 'Large',
    gender: 'Male',
    location: 'San Francisco, CA',
    price: 350,
    description: 'Cooper is a quintessential Golden Retriever: friendly, loyal, and full of life. He was rescued from a local shelter and has since shown us his incredible capacity for love. He is always the first to greet you at the door with a wagging tail and a favorite tennis ball in his mouth.',
    mainImage: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAG43o26OI_7TbCAFoMZtQ34TwdR-z3a9dGfiX9maPkknWQfx5iuDdjgZgDMRsTOCw-BTP2TUAxjrYTTd3E0OcJJmr2cKhCVZ_8e0Vv1F47dAFqN4BhjiPjUEIh7t23hbbzReYdpRxXG9W5wzdmICa9WIXdU0YTXhhMIXpkDS4TVnDpfpIp1F7z60MFCXmTt1Auvr7WzffZo0PKZetNibu0UoLfVrPGq_n8TFbtCRPBrrXROKnFTHeUgY8-UQdlD5JmmqkJCNUEDXc',
    gallery: [
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB49KpCIfkyuoBIgB1D9LRbje6Mr-TwVo-MrIs_L7ZXtKBxs59osTuNnzYS3RyhgIUrr30lp5WtA-ID7goZ6U7x_G-a4xh8MyERL79cezDMPv3wEJwWIVA51mmFoOsbEoSPVojmDG4A6kc5drvJBPsi6NRZqguk4pgRqorH5xHfkgnz9j-Xxd87I3dU6ZSFMEFR_lyXyuaPgtxYKM1c28RQT4NamHiGGA7TEPF3Xv4VNDawoTlZIZz4G6E9caMWLMKPMVOkmPsLn4c',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuB5Jpzq2gP_Sf3b46K51h68IVmZSTZapB1Jv0KfWtyHY3B0jPUmaReb3-QncnCGhJZ_IjWZY3KdLzCO-Qhhys9vt7EAlCm4zXw-5FfrEzyOecruP8IO2zcbJXdyj4QMjex2HaXP7MtBpOCjj4awmjAHRaiN_Lo9dKSM_-EY2gDTrWBrJgoPuvOYn6SshTBEt3WVjgr7HGB7Fu6JsqqPUWKsqCs6CF_BdytyQcL7hLVyF0Jplz1gAl4w0dGNmBoWyLbMivGmMgczLEg',
      'https://lh3.googleusercontent.com/aida-public/AB6AXuDvqTs6m3qw6m50ewasx4b9yDP5B8BlEVOmARRLVr6EGEnuc0rJbMKDoJyCCe0PpBQ2X5j2Piq3jimbuLpGBaDQibR4py895dQcjHxnBE2ck8_cdSbAAcAh2WYpgDzO_RZFHLm3QYwJIzj5aW4JVtjmDluoDrk-mRDQuuzG6OZ--vm7SOK9YElb7pU761zE36ClL1S7BxxE6CA0PR_Wz-y4XLyuaplCtaxXQ_sNBZNDBbT1VopwRcrNyD3zhQsvHsVNYAMzBvnqkZw'
    ],
    traits: ['Kid Friendly', 'Dog Friendly', 'House Trained', 'Loves Water', 'Fast Learner'],
    healthInfo: ['Up to date on vaccinations', 'Neutered', 'Microchipped', 'Heartworm negative'],
    isNew: true,
    energyLevel: 'High',
    weight: '65lbs'
  }
];
